import { gql } from '../../appsync-service/'

export const onCreateIncidentSubscription = gql(`
  subscription MySubscription {
      onCreateIncident {
        item {
          archived
          archived_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            email_verified
            first_name
            id
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          archived_by_id
          archived_date
          archived_text
          capture_data
          created_at
          created_by_id
          created_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            first_name
            id
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          debrief
          deleted
          deleted_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            last_login
            is_superuser
            last_name
            location {
              coordinates
              type
            }
            name
            mobile_number
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          deleted_by_id
          deleted_on
          event_id
          event {
            object_id
          }
          id
          img_file
          imported
          incident_code
          incident_messages
          location {
            coordinates
            type
          }
          message_read_list
          object_id
          reported_by_id
          resolved
          resolved_by_id
          resolved_date
          resolved_image
          resolved_text
          status_value
          tags
          subscribed_users
          triaged
          triaging_allowed_users
          type_value
          updated_at
          updated_by_id
          user_views {
            created_at
            created_by_id
            id
            incident_id
            object_id
            updated_at
            updated_by_id
            user_id
            user {
              object_id
            }
            viewed_at
          }
          updated_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            username
            updated_by_id
          }
          resolved_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            device_token
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            permission_role
            object_id
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          reported_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            device_token
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          last_message_created_at
        }
      }
  }`)

export const onUpdateIncidentSubscription = gql(`
  subscription MySubscription {
      onUpdateIncident {
        item {
          archived
          archived_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            email_verified
            first_name
            id
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          archived_by_id
          archived_date
          archived_text
          capture_data
          created_at
          created_by_id
          created_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            first_name
            id
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          debrief
          deleted
          deleted_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            last_login
            is_superuser
            last_name
            location {
              coordinates
              type
            }
            name
            mobile_number
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          deleted_by_id
          deleted_on
          event_id
          event {
            object_id
          }
          id
          img_file
          imported
          incident_code
          incident_messages
          location {
            coordinates
            type
          }
          message_read_list
          object_id
          reported_by_id
          resolved
          resolved_by_id
          resolved_date
          resolved_image
          resolved_text
          status_value
          tags
          subscribed_users
          triaged
          triaging_allowed_users
          type_value
          updated_at
          updated_by_id
          user_views {
            created_at
            created_by_id
            id
            incident_id
            object_id
            updated_at
            updated_by_id
            user_id
            user {
              object_id
            }
            viewed_at
          }
          updated_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            username
            updated_by_id
          }
          resolved_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            device_token
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            permission_role
            object_id
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          reported_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            device_token
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          last_message_created_at
        }
      }
  }`)

export const onCreateIncidentMessageSubscription = gql(`
  subscription MySubscription {
      onCreateIncidentMessage {
        item {
          attachment
          created_at
          id
          message
          object_id
          sent_at
          updated_at
          user_id
          user {
            client_id
            current_event_id
            first_name
            id
            is_active
            last_name
            name
            object_id
            username
          }
          incident_id
          incident {
            object_id
            event {
              object_id
            }
          }
          created_by_id
          created_by {
            client_id
            current_event_id
            first_name
            id
            is_active
            last_name
            name
            object_id
            username
          }
          updated_by_id
          updated_by {
            client_id
            current_event_id
            first_name
            id
            is_active
            last_name
            name
            object_id
            username
          }
        }
      }
    }
  `)

export const onCreateMarkIncidentAsReadSubscription = gql(`
  subscription MySubscription {
      onCreateMarkIncidentAsRead {
        item {
          archived
          archived_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            email_verified
            first_name
            id
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          archived_by_id
          archived_date
          archived_text
          capture_data
          created_at
          created_by_id
          created_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            first_name
            id
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          debrief
          deleted
          deleted_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            last_login
            is_superuser
            last_name
            location {
              coordinates
              type
            }
            name
            mobile_number
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          deleted_by_id
          deleted_on
          event_id
          event {
            object_id
          }
          id
          img_file
          imported
          incident_code
          incident_messages
          location {
            coordinates
            type
          }
          message_read_list
          object_id
          reported_by_id
          resolved
          resolved_by_id
          resolved_date
          resolved_image
          resolved_text
          status_value
          tags
          subscribed_users
          triaged
          triaging_allowed_users
          type_value
          updated_at
          updated_by_id
          user_views {
            created_at
            created_by_id
            id
            incident_id
            object_id
            updated_at
            updated_by_id
            user_id
            user {
              object_id
            }
            viewed_at
          }
          updated_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            username
            updated_by_id
          }
          resolved_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            device_token
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            permission_role
            object_id
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          reported_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            device_token
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          last_message_created_at
        }
      }
  }`)

export const onCreateIncidentMessageAsReadSubscription = gql(`
  subscription MySubscription {
      onCreateIncidentMessageAsRead {
        item {
          archived
          archived_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            email_verified
            first_name
            id
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          archived_by_id
          archived_date
          archived_text
          capture_data
          created_at
          created_by_id
          created_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            first_name
            id
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          debrief
          deleted
          deleted_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            last_login
            is_superuser
            last_name
            location {
              coordinates
              type
            }
            name
            mobile_number
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          deleted_by_id
          deleted_on
          event_id
          event {
            object_id
          }
          id
          img_file
          imported
          incident_code
          incident_messages
          location {
            coordinates
            type
          }
          message_read_list
          object_id
          reported_by_id
          resolved
          resolved_by_id
          resolved_date
          resolved_image
          resolved_text
          status_value
          tags
          subscribed_users
          triaged
          triaging_allowed_users
          type_value
          updated_at
          updated_by_id
          user_views {
            created_at
            created_by_id
            id
            incident_id
            object_id
            updated_at
            updated_by_id
            user_id
            user {
              object_id
            }
            viewed_at
          }
          updated_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            device_token
            email
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            username
            updated_by_id
          }
          resolved_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            device_token
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            permission_role
            object_id
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          reported_by {
            battery_percent
            battery_state
            client_id
            created_at
            created_by_id
            current_event_app_role
            current_event_id
            date_joined
            email
            device_token
            email_verified
            first_name
            id
            imported
            is_active
            is_in_geofence
            is_shift_manager
            is_staff
            is_superuser
            last_login
            last_name
            location {
              coordinates
              type
            }
            mobile_number
            name
            object_id
            permission_role
            pin
            pin_icon_url
            role
            suspended
            updated_at
            updated_by_id
            username
          }
          last_message_created_at
        }
      }
  }`)
